---
title: (4) Going Deeper with Consonants
author: Jm
date: '2020-02-03'
slug: 4-going-deeper-with-consonants
categories:
  - Phonics
tags: []
---


Going deeper with consonats sound of _v_, _j_, _w_, _q_ <!--more-->

## Key points 
* Gettig into Blending
* Looking at consonants and keywords: _v_, _j_, _w_, _q_
* Sight Words: red, and

## Materials 
* cards: v, j, w, q
* sight word cards: red, and
* crayon

## Sound of _v_, _j_

**Instructor**: The name of this letter is "vee"; the sound of this letter is v-v-v. 

What is its name?
            
what is its sound?
            
`show the v card with key word "van"`

**Instructor**: This keyword helps you to remember the letter **v**. Every time you see this letter, I want you to see the picture of a **van** in your mind, and I want you to hear the sound of the first letter. This picture will unlock the sound of this letter just as a key unlocks the door. 

`let the child draw a "van" on the card`

**Instructor**: Say its sound, not its name.

`Continue the script method with j. `

Use the following keywords to help your child learn the **v**,  **j**, **q** and **w**.

**Vv: van**  
**Jj: jet**  
**Qq: quack**    
**Ww: web**  

**Blending table for V, J, W, and Q**

v   | j  | w  |<u>qu</u>  | v  |j   |<u>qu</u>
----|----|----|----|----|----|----
va  |ja  |wa  |<u>qu</u>a  |va  |ja  | <u>qu</u>a
va n|ja b|wa g|<u>qu</u>a ck|va t|ja m|<u>qu</u>a ff
van |jab |wag |<u>qu</u>ack |vat |jam |<u>qu</u>aff

After your child maters the words in the above table, have him read the following sentences for practice. 

**Jack had jam and ham.**

**Van can wag a rag.**

**Kat can quack at a pal.**


## Sight words one red and yellow boat

one    
boat    
one boat   
red   
yellow   
and    
red and yellow   
red and yellow boat    
one red and yellow boat   



