---
title: '(2) Going Deeper with Consonants '
author: Jm
date: '2020-01-22'
slug: 2-going-deeper-with-consonants
categories:
  - Phonics
tags: []
---

Going deeper with consonats sound of _d_, _g_, _f_, _h_ <!--more-->

## Key points 
* Gettig into Blending
* Looking at consonants and keywords: _d_, _g_, _f_, _h_
* Sight Words: big, blue, ball 

## Materials 
* cards: d, g, f, h
* sight word cards: big, blue, ball
* crayon

## Sound of _d_, _g_

**Instructor**: The name of this letter is "di"; the sound of this letter is d-d-d. 

What is its name?
            
what is its sound?
            
`show the d card with key word "duck"`

**Instructor**: This keyword helps you to remember the letter **d**. Every time you see this letter, I want you to see the picture of a **duck** in your mind, and I want you to hear the sound of the first letter. This picture will unlock the sound of this letter just as a key unlocks the door. 

`let the child draw a **duck** on the card`

**Instructor**: Say its sound, not its name.

`Continue the script method with g. `

Use the following keywords to help your child learn the **d** and **g**

**Dd: duck**  
**Gg: gum**

**Blending table for D and G**

 d  | g  |  d |  g | t  |  s
----|----|----|----|----|---
da  |ga  |da  |ga  |ta  |sa
da d|ga g|da m|ga s|ta g|sa d
dad |gag |dam |gas |tag |sad

After your child maters the words in the above table, have him read the following sentences for practice. 

**Mag sat a dam.**

**Dad sat at a mat.**

**Sam sat at a dam.**

## Sound of _f_, _h_

Use the following keywords to help your child learn the **f** and **h**

Hh: hat
Ff: fish

**Blending table for H and F**

 f  | h  |  f |  h | h  
----|----|----|----|---
fa  |ha  |fa  |ha  |ha  
fa t|ha d|fa d|ha m|ha g
fat |had |fad |ham |hag 

After your child maters the words in the above table, have him read the following sentences for practice. 

**Matt had a ham.**

**Tad had a sad hat.**

**A hag had a fat ham.**

## Sight words big, blue, ball

ball

a ball

the ball

big

big ball

a big ball

the big ball

blue

blue ball

big blue ball

a big blue ball 

the big blue ball
