---
title: '(1) Simple Consonants and a Volwel'
author: Jm
date: '2020-01-22'
slug: simple-consonants-and-a-volwel
categories:
  - Phonics
tags: []
---


Phonics class specially prepared for Jason. This is Lesson one <!--more-->

## Key points 
* Gettig into Bleding
* Looking at consnants and keywords: m, s, t
* Examining the letter a 
* Sight Words: a, the, and 

## Materials 
* cards: a, m, s, t 
* sight word cards: a, the, and
* crayon

## Sound of m, s, t  
**Instructor**: Today you're going to start to read by learning all about the letter *m*

**Instructor**: The name of this letter is "em"; the sound of this letter is m-m-m. 

What is its name?
            
what is its sound?
            
`Show the m card with key word "mop"`

**Instructor**: This keyword helps you to remember the letter **m**. Every time you see this letter, I want you to see the picture of a **mop** in your mind, and I want you to hear the sound of the first letter. This picture will unlock the sound of this letter just as a key unlocks the door.  

`let the clhid draw a mop on the card`

**Instructor**: Say its sound, not its name.

`Continue the script method with s and with t.` 

## Sound of a 
For vowel sounds, we will always learn to sound all the vowel sounds together. 

Instructor: The name of this letter is "ay", but I have a surprise for you. A has three sounds. Say apple after me slowly. (Exaggerate the a and say the rest at a norma rate). This is the first sound and the first keyword. 

Now say ate. (Exaggerate the *a*) This is the second sound and the second keyword. 

Now say all. (Exaggerate the *a*) This is the third sound and the third keyword. Always remember the sound and keywords in the same order. At first, we'll be working only on the first sound (the short one).

> Associative sentence: **I ate all the apple.**

## Prefecting the blending 

Follow these steps to help your child become a master blender:

1. Hold up the flashcard with *ma* printed on it. 

2. Read the word to your child. 

As you say ma, make sure your slide both sounds together as you slide your finger underneath the word. 

3. Ask your child to say *ma*.

4. Repeat steps 1 through 3 with *sa*.

5. Repeat steps 1 through 3 with *ta*.

6. Show your child a flashcard with *ma* *t* printd on it with a definite space between *a* and *t*. 

7. Ask your child to say *ma* *t*.

8. Present the entire word *mat* with no breaks between any letters. 

9. Ask your child to say *mat*.

**Blending table for M S T **

 m  | S  |  t |  s | m
----|----|----|----|---
ma  |Sa  |ta  |sa  |ma
ma t|Sa m|ta t|sa t|ma ss
mat |Sam |tat |sat |mass

## Sight words

show the card for sight word **a, and, the**



