---
title: '(3) Going Deeper with Consonants '
author: Jm
date: '2020-01-23'
slug: 3-going-deeper-with-consonants
categories:
  - Phonics
tags: []
---


Going deeper with consonats sound of _p_, _r_, _n_, _b_ <!--more-->

## Key points 
* Gettig into Bleding
* Looking at consonants and keywords: _p_, _r_, _n_, _b_
* Sight Words: big, blue, ball 

## Materials 
* cards: p, r, n, b
* sight word cards: one, red, yellow, boat
* crayon

## Sound of _p_, _r_

**Instructor**: The name of this letter is "pee"; the sound of this letter is p-p-p. 

What is its name?
            
what is its sound?
            
`show the d card with key word "pup"`

**Instructor**: This keyword helps you to remember the letter **p**. Every time you see this letter, I want you to see the picture of a **pup** in your mind, and I want you to hear the sound of the first letter. This picture will unlock the sound of this letter just as a key unlocks the door. 

`let the clhid draw a "pup" on the card`

**Instructor**: Say its sound, not its name.

`Continue the script method with r. `

Use the following keywords to help your child learn the **p** and **r**

**Pp: pup**  
**Rr: rat**

**Blending table for P and R**

r   | p  |  r |  p | r  |  p
----|----|----|----|----|---
ra  |pa  |ra  |pa  |ra  |Pa
ra t|pa d|ra g|pa t|ra p|Pa m
rat |pad |rag |pat |rap |Pam

After your child maters the words in the above table, have him read the following sentences for practice. 

**Pam had a map.**

**Dad had a fat ram.**

**A rat had a pad.**

## Sound of _n_, _b_

Use the following keywords to help your child learn the **f** and **h**

**Nn: nap**
**Bb: bat**

**Blending table for N and B**

n   | b  |  n |  b | n  |  b
----|----|----|----|----|---
na  |ba  |na  |ba  |na  |ba
na p|ba t|na g|ba n|na b|ba d
nap |bat |nag |ban |nab |bad

After your child maters the words in the above table, have him read the following sentences for practice. 

**Dan and Ann ran.**

**Mag and Pam nab Nat.**

**Tad and Dad nab Nat.**

## Sight words big, blue, ball

one

boat

one boat

red

yellow

and

red and yellow

red and yellow boat

one red and yellow boat

the red and yellow boat



